import type { Movie } from '@/lib/types';

export const MOVIES: Movie[] = [
  {
    id: '1',
    title: 'Cosmic Odyssey',
    year: 2023,
    duration: 148,
    genres: ['Sci-Fi', 'Adventure'],
    rating: 8.5,
    synopsis: 'A team of explorers travel through a newly discovered wormhole to save humanity.',
    cast: ['Alex Ray', 'Jenna Wallace', 'Sam Cortez'],
    director: 'Eleanor Vance',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Cosmic+Odyssey',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Cosmic+Odyssey',
  },
  {
    id: '2',
    title: 'The Last Stand',
    year: 2024,
    duration: 121,
    genres: ['Action', 'Thriller'],
    rating: 7.9,
    synopsis: 'A retired special forces agent is drawn back into action to protect his family from a dangerous cartel.',
    cast: ['Marcus Thorne', 'Lena Petrova', 'David Chen'],
    director: 'James O\'Connell',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=The+Last+Stand',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=The+Last+Stand',
  },
  {
    id: '3',
    title: 'Echoes of Yesterday',
    year: 2022,
    duration: 135,
    genres: ['Drama', 'Romance'],
    rating: 8.8,
    synopsis: 'Two childhood sweethearts reconnect after decades apart, rediscovering their past and confronting their present.',
    cast: ['Sophie Miller', 'Leo Gallagher', 'Isabelle Dubois'],
    director: 'Chloé Renaud',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Echoes+of+Yesterday',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Echoes+of+Yesterday',
  },
  {
    id: '4',
    title: 'Midnight Heist',
    year: 2023,
    duration: 110,
    genres: ['Crime', 'Thriller'],
    rating: 8.1,
    synopsis: 'A group of master thieves plan an impossible heist at a high-tech casino.',
    cast: ['Jax', 'Ruby', '"The Ghost"'],
    director: 'Anonymous',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Midnight+Heist',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Midnight+Heist',
  },
  {
    id: '5',
    title: 'Laugh Riot',
    year: 2024,
    duration: 95,
    genres: ['Comedy'],
    rating: 7.5,
    synopsis: 'A struggling stand-up comedian gets a once-in-a-lifetime opportunity, but must first survive a chaotic weekend with his dysfunctional family.',
    cast: ['Benny<seg_36>" Hill', 'Debra Sparks', 'Walter Finch'],
    director: 'Patty Jenkins',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Laugh+Riot',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Laugh+Riot',
  },
  {
    id: '6',
    title: 'Cybernetic Dawn',
    year: 2025,
    duration: 155,
    genres: ['Sci-Fi', 'Action'],
    rating: 9.1,
    synopsis: 'In a futuristic city, a detective hunts a rogue android, questioning the nature of consciousness.',
    cast: ['Kaelen', 'Dr. Aris Thorne', 'Unit 734'],
    director: 'Ren Ishida',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Cybernetic+Dawn',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Cybernetic+Dawn',
  },
  {
    id: '7',
    title: 'The Hidden Kingdom',
    year: 2021,
    duration: 128,
    genres: ['Fantasy', 'Adventure'],
    rating: 8.3,
    synopsis: 'A young orphan discovers she is the heir to a magical kingdom and must reclaim her throne from an evil sorcerer.',
    cast: ['Lyra', 'Garrett', 'King Theron'],
    director: 'Guillermo del Toro',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=The+Hidden+Kingdom',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=The+Hidden+Kingdom',
  },
  {
    id: '8',
    title: 'No Way Out',
    year: 2023,
    duration: 105,
    genres: ['Horror', 'Thriller'],
    rating: 7.2,
    synopsis: 'A group of friends get trapped in a remote cabin and are stalked by an unknown entity.',
    cast: ['Mia', 'Josh', 'Chloe', 'Ben'],
    director: 'Jordan Peele',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=No+Way+Out',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=No+Way+Out',
  },
  {
    id: '9',
    title: 'The Great Escape',
    year: 2022,
    duration: 98,
    genres: ['Comedy', 'Adventure'],
    rating: 6.9,
    synopsis: 'Two mismatched brothers go on a wild road trip that changes their lives forever.',
    cast: ['Kevin Heart', 'Dwayne Johnson', 'Awkwafina'],
    director: 'Jake Kasdan',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=The+Great+Escape',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=The+Great+Escape',
  },
  {
    id: '10',
    title: 'Zero Gravity',
    year: 2024,
    duration: 142,
    genres: ['Sci-Fi', 'Drama'],
    rating: 8.9,
    synopsis: 'An astronaut becomes stranded in space and must find a way back to Earth.',
    cast: ['Dr. Evelyn Reed', 'Commander Grant', 'Mission Control'],
    director: 'Alfonso Cuarón',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Zero+Gravity',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Zero+Gravity',
  },
  {
    id: '11',
    title: 'The Crimson Blade',
    year: 2023,
    duration: 133,
    genres: ['Action', 'Fantasy'],
    rating: 8.2,
    synopsis: 'A legendary warrior seeks a mythical sword to defeat a tyrant and save his homeland.',
    cast: ['Kaito', 'Princess Anya', 'Lord Valerius'],
    director: 'Zhang Yimou',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Crimson+Blade',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Crimson+Blade',
  },
  {
    id: '12',
    title: 'Just Kidding',
    year: 2022,
    duration: 101,
    genres: ['Comedy', 'Family'],
    rating: 7.1,
    synopsis: 'A workaholic father rediscovers the joy of life when he is forced to spend a weekend with his quirky, imaginative daughter.',
    cast: ['Tom Maxwell', 'Lily Maxwell', 'Grandma Rose'],
    director: 'Nancy Meyers',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Just+Kidding',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Just+Kidding',
  },
  {
    id: '13',
    title: 'Anomaly',
    year: 2025,
    duration: 115,
    genres: ['Sci-Fi', 'Mystery', 'Thriller'],
    rating: 8.6,
    synopsis: 'A physicist discovers a temporal anomaly that could unravel reality itself.',
    cast: ['Dr. Aris Thorne', 'Detective Miller', 'The Watcher'],
    director: 'Denis Villeneuve',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Anomaly',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Anomaly',
  },
  {
    id: '14',
    title: 'Ocean\'s Heart',
    year: 2023,
    duration: 125,
    genres: ['Adventure', 'Drama'],
    rating: 8.0,
    synopsis: 'A young marine biologist fights to protect a coral reef from corporate greed.',
    cast: ['Dr. Coral Shaw', 'Jake Sullivan', 'CEO Thompson'],
    director: 'James Cameron',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=Ocean\'s+Heart',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=Ocean\'s+Heart',
  },
  {
    id: '15',
    title: 'The Final Joke',
    year: 2024,
    duration: 122,
    genres: ['Crime', 'Drama'],
    rating: 8.7,
    synopsis: 'An aging, disillusioned comedian takes a dark turn, becoming a folk hero for the downtrodden.',
    cast: ['Arthur Fleck', 'Sophie Dumond', 'Murray Franklin'],
    director: 'Todd Phillips',
    posterUrl: 'https://placehold.co/500x750/0f0f0f/e50914?text=The+Final+Joke',
    backdropUrl: 'https://placehold.co/1920x1080/0f0f0f/e50914?text=The+Final+Joke',
  },
];
